# Generated by Django 4.0.1 on 2022-01-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Звезда рейтинга', 'verbose_name_plural': 'Звезды рейтинга'},
        ),
        migrations.AddField(
            model_name='rating',
            name='slugs',
            field=models.SlugField(default='terminator', max_length=255, verbose_name='Название фильма'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(default='terminator', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
