# Generated by Django 4.0.1 on 2022-01-25 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_ratingstar_options_rating_slugs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='slugs',
        ),
    ]
