# Generated by Django 3.2 on 2023-03-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20230308_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinema',
            options={'verbose_name': 'Кинотеатр', 'verbose_name_plural': 'Кинотеатры'},
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
        migrations.AlterModelOptions(
            name='supplier_list',
            options={'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='employee',
        ),
        migrations.AddField(
            model_name='cinema',
            name='employee',
            field=models.ManyToManyField(related_name='cinema_employee', to='movies.Employees', verbose_name='работник'),
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='supplier',
        ),
        migrations.AddField(
            model_name='cinema',
            name='supplier',
            field=models.ManyToManyField(related_name='cinema_supplier', to='movies.Supplier_list', verbose_name='поставщик'),
        ),
    ]
