# Generated by Django 3.2 on 2023-03-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20230308_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cinema',
        ),
        migrations.AddField(
            model_name='movie',
            name='cinema',
            field=models.ManyToManyField(null=True, to='movies.Cinema', verbose_name='Кинотеатр'),
        ),
    ]
